# Generated by Django 5.1.2 on 2024-10-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_auto_20241027_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='paginas',
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
    ]
